#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
#include <random>
#include <stdexcept>

using std::stof;
using std::stoi;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::sort;
using std::fixed;
using std::vector;
using std::swap;
using std::runtime_error;